version: "3.7"

services:
    mysql:
        image: mysql:5.7
        container_name: ${DATABASE_HOST}
        restart: always
        environment:
            MYSQL_ROOT_USER: ${DATABASE_USER}
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_ROOT_HOST: "%"
        expose:
            - ${DATABASE_PORT}
        ports:
            - ${DATABASE_PORT}:3306
        networks:
            - book-store
        volumes:
            - ./database/setup.sql:/app/setup.sql
        command: --init-file /app/setup.sql

networks:
    book-store:
        name: book-store
        driver: bridge
